packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  prisma: true

onlyBuiltDependencies:
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - lmdb
  - msgpackr-extract
  - prisma
