packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - lmdb
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
