-- AlterTable
ALTER TABLE "ProductBlob" ALTER COLUMN "weight" SET DATA TYPE DECIMAL(14,4),
ALTER COLUMN "itemCost" SET DATA TYPE DECIMAL(14,4);

-- AlterTable
ALTER TABLE "ProductMaterialBlob" ALTER COLUMN "weight" SET DATA TYPE DECIMAL(14,4),
ALTER COLUMN "itemCost" SET DATA TYPE DECIMAL(14,4);
