app = 'dixie-api'

[_meta]
required_secrets = ['DATABASE_URL', 'REDIS_URL', 'JWT_SECRET', 'RESEND_API_KEY', 'MQTT_GATEWAY_REALY_URL', 'MQTT_GATEWAY_REALY_USER', 'MQTT_GATEWAY_REALY_PASSWORD']
domain = 'dixie-api.rockware.io'

[env]
HOST = '0.0.0.0'
LOG_LEVEL = 'info'
APP_BASE_URL = 'https://dixie.rockware.io'
BUCKET_NAME = 'rw-dixie'

[[http_service.checks]]
interval = '10s'
timeout = '2s'
grace_period = '30s'
method = 'GET'
path = '/health'
