primary_region = 'iad'

[build]

[processes]
app = 'node dist/main.js'

[env]
NODE_ENV = 'production'
PORT = '3000'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.machine]
idle_timeout = "30m"

[http_service.concurrency]
type = 'requests'
hard_limit = 250
soft_limit = 200

[[http_service.checks]]
interval = '10s'
timeout = '2s'
grace_period = '5s'
method = 'GET'
path = '/health'

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
