import type {
  EntityCatalogEntry,
  EntityCatalogField,
  SystemEntityFieldSpec,
  SystemEntitySpec,
} from "./registry.types.js";

export const ENTITY_FIELD_TYPES = [
  "TEXT",
  "NUMBER",
  "BOOLEAN",
  "DATE",
  "TIMESTAMP",
  "SELECT",
  "JSON",
  "OBJECT",
] as const;

export type EntityFieldType = (typeof ENTITY_FIELD_TYPES)[number];

export const SYSTEM_ENTITY_NAMESPACE = "imm";

export const SYSTEM_ENTITY_KEYS = {
  Site: `${SYSTEM_ENTITY_NAMESPACE}.site`,
  Workcenter: `${SYSTEM_ENTITY_NAMESPACE}.workcenter`,
  Station: `${SYSTEM_ENTITY_NAMESPACE}.station`,
  Job: `${SYSTEM_ENTITY_NAMESPACE}.job`,
  Product: `${SYSTEM_ENTITY_NAMESPACE}.product`,
  Material: `${SYSTEM_ENTITY_NAMESPACE}.material`,
  Tool: `${SYSTEM_ENTITY_NAMESPACE}.tool`,
  Customer: `${SYSTEM_ENTITY_NAMESPACE}.customer`,
  Order: `${SYSTEM_ENTITY_NAMESPACE}.order`,
  WorkOrder: `${SYSTEM_ENTITY_NAMESPACE}.workOrder`,
  Employee: `${SYSTEM_ENTITY_NAMESPACE}.employee`,
  ShiftInstance: `${SYSTEM_ENTITY_NAMESPACE}.shiftInstance`,
  StatusReason: `${SYSTEM_ENTITY_NAMESPACE}.statusReason`,
  StatusCategory: `${SYSTEM_ENTITY_NAMESPACE}.statusCategory`,
} as const;

export const SYSTEM_ENTITY_REGISTRY: readonly SystemEntitySpec[] = [
  {
    key: SYSTEM_ENTITY_KEYS.Site,
    model: "Site",
    name: "Site",
    label: "Site",
    description: "Platform-defined site record.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "name", type: "TEXT", required: true, sortOrder: 10 },
      { name: "description", type: "TEXT", sortOrder: 20 },
      { name: "timezone", type: "TEXT", sortOrder: 30 },
      {
        name: "workcenters",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Workcenter,
        relation: "workcenters",
        isList: true,
        sortOrder: 100,
      },
      {
        name: "stations",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Station,
        relation: "stations",
        isList: true,
        sortOrder: 110,
      },
    ],
  },
  {
    key: SYSTEM_ENTITY_KEYS.Workcenter,
    model: "Workcenter",
    name: "Workcenter",
    label: "Workcenter",
    description: "Platform-defined workcenter record.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "name", type: "TEXT", required: true, sortOrder: 10 },
      { name: "description", type: "TEXT", sortOrder: 20 },
      {
        name: "site",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Site,
        relation: "site",
        sortOrder: 90,
      },
      {
        name: "parent",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Workcenter,
        relation: "parent",
        sortOrder: 100,
      },
      {
        name: "children",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Workcenter,
        relation: "children",
        isList: true,
        sortOrder: 110,
      },
      {
        name: "stations",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Station,
        relation: "stations",
        isList: true,
        sortOrder: 120,
      },
    ],
  },
  {
    key: SYSTEM_ENTITY_KEYS.Station,
    model: "Station",
    name: "Station",
    label: "Station",
    description: "Platform-defined station record.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "name", type: "TEXT", required: true, sortOrder: 10 },
      { name: "description", type: "TEXT", sortOrder: 20 },
      { name: "standardCycle", type: "NUMBER", sortOrder: 30, path: "currentBlob.standardCycle" },
      { name: "downtimeDetect", type: "NUMBER", sortOrder: 40, path: "currentBlob.downtimeDetect" },
      { name: "slowDetect", type: "NUMBER", sortOrder: 50, path: "currentBlob.slowDetect" },
      { name: "inLineCalculations", type: "BOOLEAN", sortOrder: 60, path: "currentBlob.inLineCalculations" },
      { name: "inStationCalculations", type: "BOOLEAN", sortOrder: 70, path: "currentBlob.inStationCalculations" },
      {
        name: "status",
        label: "Status",
        type: "TEXT",
        description: "Live station status (FAST | SLOW | UP | DOWN) from the open state-log entry.",
        sortOrder: 72,
      },
      {
        name: "statusReasonId",
        label: "Status Reason Id",
        type: "TEXT",
        description: "Id of the StatusReason on the open state-log entry.",
        sortOrder: 74,
      },
      {
        name: "statusReason",
        label: "Status Reason",
        type: "TEXT",
        description: "Name of the StatusReason on the open state-log entry.",
        sortOrder: 76,
      },
      {
        name: "statusStartAt",
        label: "Status Start",
        type: "TIMESTAMP",
        description: "When the current status period began (open state-log entry start).",
        sortOrder: 78,
      },
      { name: "createdAt", type: "TIMESTAMP", sortOrder: 80 },
      { name: "updatedAt", type: "TIMESTAMP", sortOrder: 90 },
      { name: "deletedAt", type: "TIMESTAMP", sortOrder: 100 },
      { name: "archivedAt", type: "TIMESTAMP", sortOrder: 110 },
      {
        name: "site",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Site,
        relation: "site",
        sortOrder: 90,
      },
      {
        name: "workcenter",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Workcenter,
        relation: "workcenter",
        sortOrder: 100,
      },
      {
        name: "currentJob",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Job,
        relation: "currentJob",
        sortOrder: 110,
      },
    ],
  },
  {
    key: SYSTEM_ENTITY_KEYS.Job,
    model: "Job",
    name: "Job",
    label: "Job",
    description: "Platform-defined production job record.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "name", type: "TEXT", required: true, sortOrder: 10, path: "currentBlob.name" },
      { name: "description", type: "TEXT", sortOrder: 20, path: "currentBlob.description" },
      { name: "standardCycle", type: "NUMBER", sortOrder: 30, path: "currentBlob.standardCycle" },
      { name: "standardCycleUnit", type: "TEXT", sortOrder: 40, path: "currentBlob.standardCycleUnit" },
      { name: "productsPerCycle", type: "NUMBER", sortOrder: 50, path: "currentBlob.productsPerCycle" },
      { name: "createdAt", type: "TIMESTAMP", sortOrder: 60 },
      { name: "updatedAt", type: "TIMESTAMP", sortOrder: 70 },
      { name: "deletedAt", type: "TIMESTAMP", sortOrder: 80 },
      { name: "archivedAt", type: "TIMESTAMP", sortOrder: 90 },
      { name: "site", type: "OBJECT", targetKey: SYSTEM_ENTITY_KEYS.Site, relation: "site", sortOrder: 100 },
      {
        name: "stations",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Station,
        relation: "stations",
        isList: true,
        sortOrder: 110,
      },
      {
        name: "products",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Product,
        relation: "products",
        isList: true,
        sortOrder: 120,
      },
      {
        name: "tools",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Tool,
        relation: "tools",
        isList: true,
        sortOrder: 130,
      },
    ],
  },
  {
    key: SYSTEM_ENTITY_KEYS.Product,
    model: "Product",
    name: "Product",
    label: "Product",
    description: "Platform-defined product record.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "sku", type: "TEXT", required: true, sortOrder: 10, path: "currentBlob.sku" },
      { name: "name", type: "TEXT", sortOrder: 20, path: "currentBlob.name" },
      { name: "description", type: "TEXT", sortOrder: 30, path: "currentBlob.description" },
      { name: "externalSku", type: "TEXT", sortOrder: 40, path: "currentBlob.externalSku" },
      { name: "weight", type: "NUMBER", sortOrder: 50, path: "currentBlob.weight" },
      { name: "weightUnits", type: "TEXT", sortOrder: 60, path: "currentBlob.weightUnits" },
      { name: "createdAt", type: "TIMESTAMP", sortOrder: 70 },
      { name: "updatedAt", type: "TIMESTAMP", sortOrder: 80 },
      { name: "deletedAt", type: "TIMESTAMP", sortOrder: 90 },
      { name: "archivedAt", type: "TIMESTAMP", sortOrder: 100 },
      { name: "site", type: "OBJECT", targetKey: SYSTEM_ENTITY_KEYS.Site, relation: "site", sortOrder: 110 },
      {
        name: "materials",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Material,
        relation: "materials",
        isList: true,
        sortOrder: 120,
      },
      {
        name: "jobs",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Job,
        relation: "jobs",
        isList: true,
        sortOrder: 130,
      },
      {
        name: "workOrders",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.WorkOrder,
        relation: "workOrders",
        isList: true,
        sortOrder: 140,
      },
    ],
  },
  {
    key: SYSTEM_ENTITY_KEYS.Material,
    model: "Material",
    name: "Material",
    label: "Material",
    description: "Platform-defined material record.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "materialNumber", type: "TEXT", required: true, sortOrder: 10, path: "currentBlob.materialNumber" },
      { name: "shortCode", type: "TEXT", sortOrder: 20, path: "currentBlob.shortCode" },
      { name: "name", type: "TEXT", sortOrder: 30, path: "currentBlob.name" },
      { name: "classification", type: "TEXT", sortOrder: 40, path: "currentBlob.classification" },
      { name: "description", type: "TEXT", sortOrder: 50, path: "currentBlob.description" },
      { name: "externalNumber", type: "TEXT", sortOrder: 60, path: "currentBlob.externalNumber" },
      { name: "weightUnits", type: "TEXT", sortOrder: 70, path: "currentBlob.weightUnits" },
      { name: "createdAt", type: "TIMESTAMP", sortOrder: 80 },
      { name: "updatedAt", type: "TIMESTAMP", sortOrder: 90 },
      { name: "deletedAt", type: "TIMESTAMP", sortOrder: 100 },
      { name: "archivedAt", type: "TIMESTAMP", sortOrder: 110 },
      { name: "site", type: "OBJECT", targetKey: SYSTEM_ENTITY_KEYS.Site, relation: "site", sortOrder: 120 },
      {
        name: "products",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Product,
        relation: "products",
        isList: true,
        sortOrder: 130,
      },
    ],
  },
  {
    key: SYSTEM_ENTITY_KEYS.Tool,
    model: "Tool",
    name: "Tool",
    label: "Tool",
    description: "Platform-defined tool record.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "name", type: "TEXT", required: true, sortOrder: 10, path: "currentBlob.name" },
      { name: "description", type: "TEXT", sortOrder: 20, path: "currentBlob.description" },
      { name: "pmLimit", type: "NUMBER", sortOrder: 30, path: "currentBlob.pmLimit" },
      { name: "pmWarn", type: "NUMBER", sortOrder: 40, path: "currentBlob.pmWarn" },
      { name: "cavityCount", type: "NUMBER", sortOrder: 50, path: "currentBlob.cavityCount" },
      { name: "pmCount", type: "NUMBER", sortOrder: 60 },
      { name: "lifeCount", type: "NUMBER", sortOrder: 70 },
      { name: "createdAt", type: "TIMESTAMP", sortOrder: 80 },
      { name: "updatedAt", type: "TIMESTAMP", sortOrder: 90 },
      { name: "deletedAt", type: "TIMESTAMP", sortOrder: 100 },
      { name: "archivedAt", type: "TIMESTAMP", sortOrder: 110 },
      { name: "site", type: "OBJECT", targetKey: SYSTEM_ENTITY_KEYS.Site, relation: "site", sortOrder: 120 },
      {
        name: "jobs",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Job,
        relation: "jobs",
        isList: true,
        sortOrder: 130,
      },
    ],
  },
  {
    key: SYSTEM_ENTITY_KEYS.Customer,
    model: "Customer",
    name: "Customer",
    label: "Customer",
    description: "Platform-defined customer record.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "name", type: "TEXT", required: true, sortOrder: 10 },
      { name: "createdAt", type: "TIMESTAMP", sortOrder: 20 },
      { name: "updatedAt", type: "TIMESTAMP", sortOrder: 30 },
      { name: "deletedAt", type: "TIMESTAMP", sortOrder: 40 },
      { name: "site", type: "OBJECT", targetKey: SYSTEM_ENTITY_KEYS.Site, relation: "site", sortOrder: 50 },
      {
        name: "orders",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Order,
        relation: "orders",
        isList: true,
        sortOrder: 60,
      },
    ],
  },
  {
    key: SYSTEM_ENTITY_KEYS.Order,
    model: "Order",
    name: "Order",
    label: "Order",
    description: "Platform-defined fulfillment order record.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "orderNumber", type: "TEXT", required: true, sortOrder: 10 },
      { name: "status", type: "TEXT", sortOrder: 20 },
      { name: "previousStatus", type: "TEXT", sortOrder: 30 },
      { name: "sequence", type: "NUMBER", sortOrder: 40 },
      { name: "priority", type: "NUMBER", sortOrder: 50 },
      { name: "defaultTargetQuantity", type: "NUMBER", sortOrder: 60 },
      { name: "startDate", type: "TIMESTAMP", sortOrder: 70 },
      { name: "dueDate", type: "TIMESTAMP", sortOrder: 80 },
      { name: "createdAt", type: "TIMESTAMP", sortOrder: 90 },
      { name: "updatedAt", type: "TIMESTAMP", sortOrder: 100 },
      { name: "deletedAt", type: "TIMESTAMP", sortOrder: 110 },
      { name: "site", type: "OBJECT", targetKey: SYSTEM_ENTITY_KEYS.Site, relation: "site", sortOrder: 120 },
      {
        name: "customer",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Customer,
        relation: "customer",
        sortOrder: 130,
      },
      {
        name: "products",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Product,
        relation: "products",
        isList: true,
        sortOrder: 140,
      },
    ],
  },
  {
    key: SYSTEM_ENTITY_KEYS.WorkOrder,
    model: "WorkOrder",
    name: "WorkOrder",
    label: "Work Order",
    description: "Platform-defined production work order record.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "orderNumber", type: "TEXT", required: true, sortOrder: 10 },
      { name: "status", type: "TEXT", sortOrder: 20 },
      { name: "targetQuantity", type: "NUMBER", sortOrder: 30 },
      { name: "completedQuantity", type: "NUMBER", sortOrder: 40 },
      { name: "scrapQuantity", type: "NUMBER", sortOrder: 50 },
      { name: "dueDate", type: "TIMESTAMP", sortOrder: 60 },
      { name: "priority", type: "NUMBER", sortOrder: 70 },
      { name: "createdAt", type: "TIMESTAMP", sortOrder: 80 },
      { name: "updatedAt", type: "TIMESTAMP", sortOrder: 90 },
      { name: "deletedAt", type: "TIMESTAMP", sortOrder: 100 },
      { name: "site", type: "OBJECT", targetKey: SYSTEM_ENTITY_KEYS.Site, relation: "site", sortOrder: 110 },
      { name: "job", type: "OBJECT", targetKey: SYSTEM_ENTITY_KEYS.Job, relation: "job", sortOrder: 120 },
      {
        name: "product",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Product,
        relation: "product",
        sortOrder: 130,
      },
    ],
  },
  {
    key: SYSTEM_ENTITY_KEYS.Employee,
    model: "Employee",
    name: "Employee",
    label: "Employee",
    description: "Platform-defined employee record.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "status", type: "TEXT", sortOrder: 10 },
      { name: "firstName", type: "TEXT", sortOrder: 20, path: "version.firstName" },
      { name: "lastName", type: "TEXT", sortOrder: 30, path: "version.lastName" },
      { name: "employeeNumber", type: "TEXT", sortOrder: 40, path: "version.employeeNumber" },
      { name: "createdAt", type: "TIMESTAMP", sortOrder: 50 },
      { name: "updatedAt", type: "TIMESTAMP", sortOrder: 60 },
      {
        name: "sites",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Site,
        relation: "sites",
        isList: true,
        sortOrder: 70,
      },
    ],
  },
  {
    key: SYSTEM_ENTITY_KEYS.ShiftInstance,
    model: "ShiftInstance",
    name: "ShiftInstance",
    label: "Shift Instance",
    description: "Materialized shift window.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "shiftName", type: "TEXT", required: true, sortOrder: 10 },
      { name: "businessDate", type: "DATE", sortOrder: 20 },
      { name: "startTime", type: "TIMESTAMP", sortOrder: 30 },
      { name: "endTime", type: "TIMESTAMP", sortOrder: 40 },
      { name: "site", type: "OBJECT", targetKey: SYSTEM_ENTITY_KEYS.Site, relation: "site", sortOrder: 50 },
      {
        name: "workcenter",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.Workcenter,
        relation: "workcenter",
        sortOrder: 60,
      },
    ],
  },
  {
    key: SYSTEM_ENTITY_KEYS.StatusReason,
    model: "StatusReason",
    name: "StatusReason",
    label: "Status Reason",
    description: "Platform-defined status reason record.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "name", type: "TEXT", required: true, sortOrder: 10 },
      { name: "isPlannedDown", type: "BOOLEAN", sortOrder: 20 },
      { name: "createdAt", type: "TIMESTAMP", sortOrder: 30 },
      { name: "updatedAt", type: "TIMESTAMP", sortOrder: 40 },
      { name: "archivedAt", type: "TIMESTAMP", sortOrder: 50 },
      { name: "site", type: "OBJECT", targetKey: SYSTEM_ENTITY_KEYS.Site, relation: "site", sortOrder: 60 },
      {
        name: "category",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.StatusCategory,
        relation: "category",
        sortOrder: 70,
      },
    ],
  },
  {
    key: SYSTEM_ENTITY_KEYS.StatusCategory,
    model: "StatusCategory",
    name: "StatusCategory",
    label: "Status Category",
    description: "Platform-defined status category record.",
    fields: [
      { name: "id", type: "TEXT", sortOrder: 0 },
      { name: "name", type: "TEXT", required: true, sortOrder: 10 },
      { name: "createdAt", type: "TIMESTAMP", sortOrder: 20 },
      { name: "updatedAt", type: "TIMESTAMP", sortOrder: 30 },
      { name: "deletedAt", type: "TIMESTAMP", sortOrder: 40 },
      { name: "archivedAt", type: "TIMESTAMP", sortOrder: 50 },
      { name: "site", type: "OBJECT", targetKey: SYSTEM_ENTITY_KEYS.Site, relation: "site", sortOrder: 60 },
      {
        name: "statusReasons",
        type: "OBJECT",
        targetKey: SYSTEM_ENTITY_KEYS.StatusReason,
        relation: "statusReasons",
        isList: true,
        sortOrder: 70,
      },
    ],
  },
];

export function systemEntityCatalogEntries(includeFields = true): EntityCatalogEntry[] {
  return SYSTEM_ENTITY_REGISTRY.map((entity) => ({
    id: entity.key,
    key: entity.key,
    name: entity.name,
    label: entity.label,
    description: entity.description,
    origin: "system",
    backend: "record",
    model: entity.model,
    ...(includeFields ? { fields: entity.fields.map(systemFieldToCatalogField) } : {}),
  }));
}

export function systemEntityCatalogEntryByKey(key: string, includeFields = true): EntityCatalogEntry | null {
  return systemEntityCatalogEntries(includeFields).find((entry) => entry.key === key) ?? null;
}

export function systemRelationTargets(): Map<string, Map<string, string>> {
  const targetsByModel = new Map<string, Map<string, string>>();
  const modelByKey = new Map(SYSTEM_ENTITY_REGISTRY.map((entity) => [entity.key, entity.model]));

  for (const entity of SYSTEM_ENTITY_REGISTRY) {
    const targets = new Map<string, string>();
    for (const field of entity.fields) {
      if (!field.relation || !field.targetKey) continue;
      const targetModel = modelByKey.get(field.targetKey);
      if (targetModel) targets.set(field.relation, targetModel);
    }
    targetsByModel.set(entity.model, targets);
  }

  return targetsByModel;
}

function systemFieldToCatalogField(field: SystemEntityFieldSpec): EntityCatalogField {
  return {
    key: field.name,
    name: field.name,
    label: field.label ?? field.name,
    type: field.type,
    description: field.description ?? null,
    required: field.required ?? false,
    isList: field.isList ?? false,
    path: field.path ?? field.name,
    relation: field.relation && field.targetKey ? { key: field.relation, targetKey: field.targetKey } : null,
    sortOrder: field.sortOrder,
  };
}
