-- Rename *Blob -> *Version (data-preserving). Auto-generated from live schema.

-- Columns
ALTER TABLE "Cycle" RENAME COLUMN "jobBlobId" TO "jobVersionId";
ALTER TABLE "Cycle" RENAME COLUMN "stationBlobId" TO "stationVersionId";
ALTER TABLE "InventoryItem" RENAME COLUMN "jobProductBlobId" TO "jobProductVersionId";
ALTER TABLE "InventoryItem" RENAME COLUMN "productBlobId" TO "productVersionId";
ALTER TABLE "InventoryItem" RENAME COLUMN "toolBlobId" TO "toolVersionId";
ALTER TABLE "InventoryItem" RENAME COLUMN "toolCavityBlobId" TO "toolCavityVersionId";
ALTER TABLE "ItemDispositionLog" RENAME COLUMN "jobProductBlobId" TO "jobProductVersionId";
ALTER TABLE "ItemDispositionLog" RENAME COLUMN "productBlobId" TO "productVersionId";
ALTER TABLE "ItemDispositionLog" RENAME COLUMN "stationBlobId" TO "stationVersionId";
ALTER TABLE "ItemDispositionLog" RENAME COLUMN "toolBlobId" TO "toolVersionId";
ALTER TABLE "ItemDispositionLog" RENAME COLUMN "toolCavityBlobId" TO "toolCavityVersionId";
ALTER TABLE "Job" RENAME COLUMN "currentBlobId" TO "currentVersionId";
ALTER TABLE "JobProduct" RENAME COLUMN "currentBlobId" TO "currentVersionId";
ALTER TABLE "Material" RENAME COLUMN "currentBlobId" TO "currentVersionId";
ALTER TABLE "Product" RENAME COLUMN "currentBlobId" TO "currentVersionId";
ALTER TABLE "ProductMaterial" RENAME COLUMN "currentBlobId" TO "currentVersionId";
ALTER TABLE "ProductMaterialBlob" RENAME COLUMN "materialBlobId" TO "materialVersionId";
ALTER TABLE "ProductMaterialBlob" RENAME COLUMN "productBlobId" TO "productVersionId";
ALTER TABLE "Station" RENAME COLUMN "currentBlobId" TO "currentVersionId";
ALTER TABLE "StationJobLog" RENAME COLUMN "jobBlobId" TO "jobVersionId";
ALTER TABLE "StationStateLog" RENAME COLUMN "jobBlobId" TO "jobVersionId";
ALTER TABLE "StationStateLog" RENAME COLUMN "stationBlobId" TO "stationVersionId";
ALTER TABLE "Tool" RENAME COLUMN "currentBlobId" TO "currentVersionId";
ALTER TABLE "ToolCavity" RENAME COLUMN "currentBlobId" TO "currentVersionId";

-- Indexes (non-constraint)
ALTER INDEX "Cycle_jobBlobId_idx" RENAME TO "Cycle_jobVersionId_idx";
ALTER INDEX "InventoryItem_jobProductBlobId_idx" RENAME TO "InventoryItem_jobProductVersionId_idx";
ALTER INDEX "InventoryItem_productBlobId_idx" RENAME TO "InventoryItem_productVersionId_idx";
ALTER INDEX "InventoryItem_toolBlobId_idx" RENAME TO "InventoryItem_toolVersionId_idx";
ALTER INDEX "InventoryItem_toolCavityBlobId_idx" RENAME TO "InventoryItem_toolCavityVersionId_idx";
ALTER INDEX "JobBlob_jobId_idx" RENAME TO "JobVersion_jobId_idx";
ALTER INDEX "JobBlob_jobId_version_key" RENAME TO "JobVersion_jobId_version_key";
ALTER INDEX "JobProductBlob_jobProductId_idx" RENAME TO "JobProductVersion_jobProductId_idx";
ALTER INDEX "JobProductBlob_jobProductId_version_key" RENAME TO "JobProductVersion_jobProductId_version_key";
ALTER INDEX "JobProduct_currentBlobId_key" RENAME TO "JobProduct_currentVersionId_key";
ALTER INDEX "Job_currentBlobId_key" RENAME TO "Job_currentVersionId_key";
ALTER INDEX "MaterialBlob_materialId_idx" RENAME TO "MaterialVersion_materialId_idx";
ALTER INDEX "MaterialBlob_materialId_version_key" RENAME TO "MaterialVersion_materialId_version_key";
ALTER INDEX "Material_currentBlobId_key" RENAME TO "Material_currentVersionId_key";
ALTER INDEX "ProductBlob_productId_idx" RENAME TO "ProductVersion_productId_idx";
ALTER INDEX "ProductBlob_productId_version_key" RENAME TO "ProductVersion_productId_version_key";
ALTER INDEX "ProductMaterialBlob_materialBlobId_idx" RENAME TO "ProductMaterialVersion_materialVersionId_idx";
ALTER INDEX "ProductMaterialBlob_productMaterialId_idx" RENAME TO "ProductMaterialVersion_productMaterialId_idx";
ALTER INDEX "ProductMaterialBlob_productMaterialId_version_key" RENAME TO "ProductMaterialVersion_productMaterialId_version_key";
ALTER INDEX "ProductMaterial_currentBlobId_key" RENAME TO "ProductMaterial_currentVersionId_key";
ALTER INDEX "Product_currentBlobId_key" RENAME TO "Product_currentVersionId_key";
ALTER INDEX "StationBlob_stationId_idx" RENAME TO "StationVersion_stationId_idx";
ALTER INDEX "StationBlob_stationId_version_key" RENAME TO "StationVersion_stationId_version_key";
ALTER INDEX "StationStateLog_jobBlobId_idx" RENAME TO "StationStateLog_jobVersionId_idx";
ALTER INDEX "Station_currentBlobId_key" RENAME TO "Station_currentVersionId_key";
ALTER INDEX "ToolBlob_toolId_idx" RENAME TO "ToolVersion_toolId_idx";
ALTER INDEX "ToolBlob_toolId_version_key" RENAME TO "ToolVersion_toolId_version_key";
ALTER INDEX "ToolCavityBlob_toolCavityId_idx" RENAME TO "ToolCavityVersion_toolCavityId_idx";
ALTER INDEX "ToolCavityBlob_toolCavityId_version_key" RENAME TO "ToolCavityVersion_toolCavityId_version_key";
ALTER INDEX "ToolCavity_currentBlobId_key" RENAME TO "ToolCavity_currentVersionId_key";
ALTER INDEX "Tool_currentBlobId_key" RENAME TO "Tool_currentVersionId_key";
ALTER INDEX "_CycleToToolBlob_B_index" RENAME TO "_CycleToToolVersion_B_index";
ALTER INDEX "_InventoryItemToProductMaterialBlob_B_index" RENAME TO "_InventoryItemToProductMaterialVersion_B_index";
ALTER INDEX "_ItemDispositionLogToProductMaterialBlob_B_index" RENAME TO "_ItemDispositionLogToProductMaterialVersion_B_index";

-- Tables
ALTER TABLE "JobBlob" RENAME TO "JobVersion";
ALTER TABLE "JobProductBlob" RENAME TO "JobProductVersion";
ALTER TABLE "MaterialBlob" RENAME TO "MaterialVersion";
ALTER TABLE "ProductBlob" RENAME TO "ProductVersion";
ALTER TABLE "ProductMaterialBlob" RENAME TO "ProductMaterialVersion";
ALTER TABLE "StationBlob" RENAME TO "StationVersion";
ALTER TABLE "ToolBlob" RENAME TO "ToolVersion";
ALTER TABLE "ToolCavityBlob" RENAME TO "ToolCavityVersion";
ALTER TABLE "_CycleToToolBlob" RENAME TO "_CycleToToolVersion";
ALTER TABLE "_InventoryItemToProductMaterialBlob" RENAME TO "_InventoryItemToProductMaterialVersion";
ALTER TABLE "_ItemDispositionLogToProductMaterialBlob" RENAME TO "_ItemDispositionLogToProductMaterialVersion";

-- Constraints (FK/PK) — table referenced by its NEW name
ALTER TABLE "Cycle" RENAME CONSTRAINT "Cycle_jobBlobId_fkey" TO "Cycle_jobVersionId_fkey";
ALTER TABLE "Cycle" RENAME CONSTRAINT "Cycle_jobBlobId_not_null" TO "Cycle_jobVersionId_not_null";
ALTER TABLE "Cycle" RENAME CONSTRAINT "Cycle_stationBlobId_fkey" TO "Cycle_stationVersionId_fkey";
ALTER TABLE "InventoryItem" RENAME CONSTRAINT "InventoryItem_jobProductBlobId_fkey" TO "InventoryItem_jobProductVersionId_fkey";
ALTER TABLE "InventoryItem" RENAME CONSTRAINT "InventoryItem_productBlobId_fkey" TO "InventoryItem_productVersionId_fkey";
ALTER TABLE "InventoryItem" RENAME CONSTRAINT "InventoryItem_productBlobId_not_null" TO "InventoryItem_productVersionId_not_null";
ALTER TABLE "InventoryItem" RENAME CONSTRAINT "InventoryItem_toolBlobId_fkey" TO "InventoryItem_toolVersionId_fkey";
ALTER TABLE "InventoryItem" RENAME CONSTRAINT "InventoryItem_toolCavityBlobId_fkey" TO "InventoryItem_toolCavityVersionId_fkey";
ALTER TABLE "ItemDispositionLog" RENAME CONSTRAINT "ItemDispositionLog_jobProductBlobId_fkey" TO "ItemDispositionLog_jobProductVersionId_fkey";
ALTER TABLE "ItemDispositionLog" RENAME CONSTRAINT "ItemDispositionLog_productBlobId_fkey" TO "ItemDispositionLog_productVersionId_fkey";
ALTER TABLE "ItemDispositionLog" RENAME CONSTRAINT "ItemDispositionLog_productBlobId_not_null" TO "ItemDispositionLog_productVersionId_not_null";
ALTER TABLE "ItemDispositionLog" RENAME CONSTRAINT "ItemDispositionLog_stationBlobId_fkey" TO "ItemDispositionLog_stationVersionId_fkey";
ALTER TABLE "ItemDispositionLog" RENAME CONSTRAINT "ItemDispositionLog_toolBlobId_fkey" TO "ItemDispositionLog_toolVersionId_fkey";
ALTER TABLE "ItemDispositionLog" RENAME CONSTRAINT "ItemDispositionLog_toolCavityBlobId_fkey" TO "ItemDispositionLog_toolCavityVersionId_fkey";
ALTER TABLE "Job" RENAME CONSTRAINT "Job_currentBlobId_fkey" TO "Job_currentVersionId_fkey";
ALTER TABLE "JobVersion" RENAME CONSTRAINT "JobBlob_attrs_not_null" TO "JobVersion_attrs_not_null";
ALTER TABLE "JobVersion" RENAME CONSTRAINT "JobBlob_createdAt_not_null" TO "JobVersion_createdAt_not_null";
ALTER TABLE "JobVersion" RENAME CONSTRAINT "JobBlob_id_not_null" TO "JobVersion_id_not_null";
ALTER TABLE "JobVersion" RENAME CONSTRAINT "JobBlob_jobId_fkey" TO "JobVersion_jobId_fkey";
ALTER TABLE "JobVersion" RENAME CONSTRAINT "JobBlob_jobId_not_null" TO "JobVersion_jobId_not_null";
ALTER TABLE "JobVersion" RENAME CONSTRAINT "JobBlob_name_not_null" TO "JobVersion_name_not_null";
ALTER TABLE "JobVersion" RENAME CONSTRAINT "JobBlob_pkey" TO "JobVersion_pkey";
ALTER TABLE "JobVersion" RENAME CONSTRAINT "JobBlob_productsPerCycle_not_null" TO "JobVersion_productsPerCycle_not_null";
ALTER TABLE "JobVersion" RENAME CONSTRAINT "JobBlob_standardCycleUnit_not_null" TO "JobVersion_standardCycleUnit_not_null";
ALTER TABLE "JobVersion" RENAME CONSTRAINT "JobBlob_version_not_null" TO "JobVersion_version_not_null";
ALTER TABLE "JobProduct" RENAME CONSTRAINT "JobProduct_currentBlobId_fkey" TO "JobProduct_currentVersionId_fkey";
ALTER TABLE "JobProductVersion" RENAME CONSTRAINT "JobProductBlob_createdAt_not_null" TO "JobProductVersion_createdAt_not_null";
ALTER TABLE "JobProductVersion" RENAME CONSTRAINT "JobProductBlob_id_not_null" TO "JobProductVersion_id_not_null";
ALTER TABLE "JobProductVersion" RENAME CONSTRAINT "JobProductBlob_isActive_not_null" TO "JobProductVersion_isActive_not_null";
ALTER TABLE "JobProductVersion" RENAME CONSTRAINT "JobProductBlob_jobProductId_fkey" TO "JobProductVersion_jobProductId_fkey";
ALTER TABLE "JobProductVersion" RENAME CONSTRAINT "JobProductBlob_jobProductId_not_null" TO "JobProductVersion_jobProductId_not_null";
ALTER TABLE "JobProductVersion" RENAME CONSTRAINT "JobProductBlob_pkey" TO "JobProductVersion_pkey";
ALTER TABLE "JobProductVersion" RENAME CONSTRAINT "JobProductBlob_quantity_not_null" TO "JobProductVersion_quantity_not_null";
ALTER TABLE "JobProductVersion" RENAME CONSTRAINT "JobProductBlob_version_not_null" TO "JobProductVersion_version_not_null";
ALTER TABLE "Material" RENAME CONSTRAINT "Material_currentBlobId_fkey" TO "Material_currentVersionId_fkey";
ALTER TABLE "MaterialVersion" RENAME CONSTRAINT "MaterialBlob_attrs_not_null" TO "MaterialVersion_attrs_not_null";
ALTER TABLE "MaterialVersion" RENAME CONSTRAINT "MaterialBlob_createdAt_not_null" TO "MaterialVersion_createdAt_not_null";
ALTER TABLE "MaterialVersion" RENAME CONSTRAINT "MaterialBlob_id_not_null" TO "MaterialVersion_id_not_null";
ALTER TABLE "MaterialVersion" RENAME CONSTRAINT "MaterialBlob_materialId_fkey" TO "MaterialVersion_materialId_fkey";
ALTER TABLE "MaterialVersion" RENAME CONSTRAINT "MaterialBlob_materialId_not_null" TO "MaterialVersion_materialId_not_null";
ALTER TABLE "MaterialVersion" RENAME CONSTRAINT "MaterialBlob_materialNumber_not_null" TO "MaterialVersion_materialNumber_not_null";
ALTER TABLE "MaterialVersion" RENAME CONSTRAINT "MaterialBlob_pkey" TO "MaterialVersion_pkey";
ALTER TABLE "MaterialVersion" RENAME CONSTRAINT "MaterialBlob_version_not_null" TO "MaterialVersion_version_not_null";
ALTER TABLE "Product" RENAME CONSTRAINT "Product_currentBlobId_fkey" TO "Product_currentVersionId_fkey";
ALTER TABLE "ProductVersion" RENAME CONSTRAINT "ProductBlob_attrs_not_null" TO "ProductVersion_attrs_not_null";
ALTER TABLE "ProductVersion" RENAME CONSTRAINT "ProductBlob_createdAt_not_null" TO "ProductVersion_createdAt_not_null";
ALTER TABLE "ProductVersion" RENAME CONSTRAINT "ProductBlob_id_not_null" TO "ProductVersion_id_not_null";
ALTER TABLE "ProductVersion" RENAME CONSTRAINT "ProductBlob_pkey" TO "ProductVersion_pkey";
ALTER TABLE "ProductVersion" RENAME CONSTRAINT "ProductBlob_productId_fkey" TO "ProductVersion_productId_fkey";
ALTER TABLE "ProductVersion" RENAME CONSTRAINT "ProductBlob_productId_not_null" TO "ProductVersion_productId_not_null";
ALTER TABLE "ProductVersion" RENAME CONSTRAINT "ProductBlob_sku_not_null" TO "ProductVersion_sku_not_null";
ALTER TABLE "ProductVersion" RENAME CONSTRAINT "ProductBlob_version_not_null" TO "ProductVersion_version_not_null";
ALTER TABLE "ProductMaterial" RENAME CONSTRAINT "ProductMaterial_currentBlobId_fkey" TO "ProductMaterial_currentVersionId_fkey";
ALTER TABLE "ProductMaterialVersion" RENAME CONSTRAINT "ProductMaterialBlob_attrs_not_null" TO "ProductMaterialVersion_attrs_not_null";
ALTER TABLE "ProductMaterialVersion" RENAME CONSTRAINT "ProductMaterialBlob_createdAt_not_null" TO "ProductMaterialVersion_createdAt_not_null";
ALTER TABLE "ProductMaterialVersion" RENAME CONSTRAINT "ProductMaterialBlob_id_not_null" TO "ProductMaterialVersion_id_not_null";
ALTER TABLE "ProductMaterialVersion" RENAME CONSTRAINT "ProductMaterialBlob_materialBlobId_fkey" TO "ProductMaterialVersion_materialVersionId_fkey";
ALTER TABLE "ProductMaterialVersion" RENAME CONSTRAINT "ProductMaterialBlob_materialBlobId_not_null" TO "ProductMaterialVersion_materialVersionId_not_null";
ALTER TABLE "ProductMaterialVersion" RENAME CONSTRAINT "ProductMaterialBlob_pkey" TO "ProductMaterialVersion_pkey";
ALTER TABLE "ProductMaterialVersion" RENAME CONSTRAINT "ProductMaterialBlob_productBlobId_fkey" TO "ProductMaterialVersion_productVersionId_fkey";
ALTER TABLE "ProductMaterialVersion" RENAME CONSTRAINT "ProductMaterialBlob_productBlobId_not_null" TO "ProductMaterialVersion_productVersionId_not_null";
ALTER TABLE "ProductMaterialVersion" RENAME CONSTRAINT "ProductMaterialBlob_productMaterialId_fkey" TO "ProductMaterialVersion_productMaterialId_fkey";
ALTER TABLE "ProductMaterialVersion" RENAME CONSTRAINT "ProductMaterialBlob_productMaterialId_not_null" TO "ProductMaterialVersion_productMaterialId_not_null";
ALTER TABLE "ProductMaterialVersion" RENAME CONSTRAINT "ProductMaterialBlob_version_not_null" TO "ProductMaterialVersion_version_not_null";
ALTER TABLE "Station" RENAME CONSTRAINT "Station_currentBlobId_fkey" TO "Station_currentVersionId_fkey";
ALTER TABLE "StationVersion" RENAME CONSTRAINT "StationBlob_createdAt_not_null" TO "StationVersion_createdAt_not_null";
ALTER TABLE "StationVersion" RENAME CONSTRAINT "StationBlob_downtimeDetectUnit_not_null" TO "StationVersion_downtimeDetectUnit_not_null";
ALTER TABLE "StationVersion" RENAME CONSTRAINT "StationBlob_id_not_null" TO "StationVersion_id_not_null";
ALTER TABLE "StationVersion" RENAME CONSTRAINT "StationBlob_inLineCalculations_not_null" TO "StationVersion_inLineCalculations_not_null";
ALTER TABLE "StationVersion" RENAME CONSTRAINT "StationBlob_inStationCalculations_not_null" TO "StationVersion_inStationCalculations_not_null";
ALTER TABLE "StationVersion" RENAME CONSTRAINT "StationBlob_pkey" TO "StationVersion_pkey";
ALTER TABLE "StationVersion" RENAME CONSTRAINT "StationBlob_processTypeId_fkey" TO "StationVersion_processTypeId_fkey";
ALTER TABLE "StationVersion" RENAME CONSTRAINT "StationBlob_slowDetectUnit_not_null" TO "StationVersion_slowDetectUnit_not_null";
ALTER TABLE "StationVersion" RENAME CONSTRAINT "StationBlob_stationId_fkey" TO "StationVersion_stationId_fkey";
ALTER TABLE "StationVersion" RENAME CONSTRAINT "StationBlob_stationId_not_null" TO "StationVersion_stationId_not_null";
ALTER TABLE "StationVersion" RENAME CONSTRAINT "StationBlob_version_not_null" TO "StationVersion_version_not_null";
ALTER TABLE "StationJobLog" RENAME CONSTRAINT "StationJobLog_jobBlobId_not_null" TO "StationJobLog_jobVersionId_not_null";
ALTER TABLE "StationStateLog" RENAME CONSTRAINT "StationStateLog_jobBlobId_fkey" TO "StationStateLog_jobVersionId_fkey";
ALTER TABLE "StationStateLog" RENAME CONSTRAINT "StationStateLog_stationBlobId_fkey" TO "StationStateLog_stationVersionId_fkey";
ALTER TABLE "Tool" RENAME CONSTRAINT "Tool_currentBlobId_fkey" TO "Tool_currentVersionId_fkey";
ALTER TABLE "ToolVersion" RENAME CONSTRAINT "ToolBlob_attrs_not_null" TO "ToolVersion_attrs_not_null";
ALTER TABLE "ToolVersion" RENAME CONSTRAINT "ToolBlob_createdAt_not_null" TO "ToolVersion_createdAt_not_null";
ALTER TABLE "ToolVersion" RENAME CONSTRAINT "ToolBlob_id_not_null" TO "ToolVersion_id_not_null";
ALTER TABLE "ToolVersion" RENAME CONSTRAINT "ToolBlob_name_not_null" TO "ToolVersion_name_not_null";
ALTER TABLE "ToolVersion" RENAME CONSTRAINT "ToolBlob_pkey" TO "ToolVersion_pkey";
ALTER TABLE "ToolVersion" RENAME CONSTRAINT "ToolBlob_toolId_fkey" TO "ToolVersion_toolId_fkey";
ALTER TABLE "ToolVersion" RENAME CONSTRAINT "ToolBlob_toolId_not_null" TO "ToolVersion_toolId_not_null";
ALTER TABLE "ToolVersion" RENAME CONSTRAINT "ToolBlob_version_not_null" TO "ToolVersion_version_not_null";
ALTER TABLE "ToolCavity" RENAME CONSTRAINT "ToolCavity_currentBlobId_fkey" TO "ToolCavity_currentVersionId_fkey";
ALTER TABLE "ToolCavityVersion" RENAME CONSTRAINT "ToolCavityBlob_createdAt_not_null" TO "ToolCavityVersion_createdAt_not_null";
ALTER TABLE "ToolCavityVersion" RENAME CONSTRAINT "ToolCavityBlob_id_not_null" TO "ToolCavityVersion_id_not_null";
ALTER TABLE "ToolCavityVersion" RENAME CONSTRAINT "ToolCavityBlob_name_not_null" TO "ToolCavityVersion_name_not_null";
ALTER TABLE "ToolCavityVersion" RENAME CONSTRAINT "ToolCavityBlob_pkey" TO "ToolCavityVersion_pkey";
ALTER TABLE "ToolCavityVersion" RENAME CONSTRAINT "ToolCavityBlob_toolCavityId_fkey" TO "ToolCavityVersion_toolCavityId_fkey";
ALTER TABLE "ToolCavityVersion" RENAME CONSTRAINT "ToolCavityBlob_toolCavityId_not_null" TO "ToolCavityVersion_toolCavityId_not_null";
ALTER TABLE "ToolCavityVersion" RENAME CONSTRAINT "ToolCavityBlob_version_not_null" TO "ToolCavityVersion_version_not_null";
ALTER TABLE "_CycleToToolVersion" RENAME CONSTRAINT "_CycleToToolBlob_AB_pkey" TO "_CycleToToolVersion_AB_pkey";
ALTER TABLE "_CycleToToolVersion" RENAME CONSTRAINT "_CycleToToolBlob_A_fkey" TO "_CycleToToolVersion_A_fkey";
ALTER TABLE "_CycleToToolVersion" RENAME CONSTRAINT "_CycleToToolBlob_A_not_null" TO "_CycleToToolVersion_A_not_null";
ALTER TABLE "_CycleToToolVersion" RENAME CONSTRAINT "_CycleToToolBlob_B_fkey" TO "_CycleToToolVersion_B_fkey";
ALTER TABLE "_CycleToToolVersion" RENAME CONSTRAINT "_CycleToToolBlob_B_not_null" TO "_CycleToToolVersion_B_not_null";
ALTER TABLE "_InventoryItemToProductMaterialVersion" RENAME CONSTRAINT "_InventoryItemToProductMaterialBlob_AB_pkey" TO "_InventoryItemToProductMaterialVersion_AB_pkey";
ALTER TABLE "_InventoryItemToProductMaterialVersion" RENAME CONSTRAINT "_InventoryItemToProductMaterialBlob_A_fkey" TO "_InventoryItemToProductMaterialVersion_A_fkey";
ALTER TABLE "_InventoryItemToProductMaterialVersion" RENAME CONSTRAINT "_InventoryItemToProductMaterialBlob_A_not_null" TO "_InventoryItemToProductMaterialVersion_A_not_null";
ALTER TABLE "_InventoryItemToProductMaterialVersion" RENAME CONSTRAINT "_InventoryItemToProductMaterialBlob_B_fkey" TO "_InventoryItemToProductMaterialVersion_B_fkey";
ALTER TABLE "_InventoryItemToProductMaterialVersion" RENAME CONSTRAINT "_InventoryItemToProductMaterialBlob_B_not_null" TO "_InventoryItemToProductMaterialVersion_B_not_null";
ALTER TABLE "_ItemDispositionLogToProductMaterialVersion" RENAME CONSTRAINT "_ItemDispositionLogToProductMaterialBlob_AB_pkey" TO "_ItemDispositionLogToProductMaterialVersion_AB_pkey";
ALTER TABLE "_ItemDispositionLogToProductMaterialVersion" RENAME CONSTRAINT "_ItemDispositionLogToProductMaterialBlob_A_fkey" TO "_ItemDispositionLogToProductMaterialVersion_A_fkey";
ALTER TABLE "_ItemDispositionLogToProductMaterialVersion" RENAME CONSTRAINT "_ItemDispositionLogToProductMaterialBlob_A_not_null" TO "_ItemDispositionLogToProductMaterialVersion_A_not_null";
ALTER TABLE "_ItemDispositionLogToProductMaterialVersion" RENAME CONSTRAINT "_ItemDispositionLogToProductMaterialBlob_B_fkey" TO "_ItemDispositionLogToProductMaterialVersion_B_fkey";
ALTER TABLE "_ItemDispositionLogToProductMaterialVersion" RENAME CONSTRAINT "_ItemDispositionLogToProductMaterialBlob_B_not_null" TO "_ItemDispositionLogToProductMaterialVersion_B_not_null";
